name: Build and Release VSCode Extension

on:
  push:
    branches:
      - main

permissions:
  contents: write   # Necessary for GitHub Releases

jobs:
  release:
    if: startsWith(github.event.head_commit.message, '[RELEASE]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Build VSIX
        run: vsce package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.sha }}
          name: Release from commit ${{ github.sha }}
          body: ${{ github.event.head_commit.message }}
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to OpenVSX
        run: npx ovsx publish *.vsix -p ${{ secrets.OPENVSX_TOKEN }}
